export PATH=/usr/local/git/current/bin:/usr/local/opt/python/libexec/bin
export PATH=/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
export PATH=/usr/local/bin:/usr/local/opt/gnu-sed/libexec/gnubin:~/google-cloud-sdk/bin:$PATH
export PATH=/Users/djrut/bin:/opt/homebrew/bin:$PATH
export DIRENV_WARN_TIMEOUT=10s
export JAVA_HOME=/Library/Java/Home
export SYSTEM_VERSION_COMPAT=1
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$(pyenv root)/shims:$PATH"
export PYTHON_CONFIGURE_OPTS="--enable-framework"
